language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "4.8"
  - "6"
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run lint:all
  - npm test
after_success: npm run coverage
